//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suu.FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityHashtag
    {
        public int Id { get; set; }
        public Nullable<long> status_id { get; set; }
        public Nullable<int> hashtag_id { get; set; }
    
        public virtual Hashtag Hashtag { get; set; }
        public virtual Status Status { get; set; }
    }
}
